export default {
  BOARD_JOIN: 'BOARD_JOIN',
  BOARD_LEAVE: 'BOARD_LEAVE',
  BOARD_CREATE_LIST: 'BOARD_CREATE_LIST',
  BOARD_CREATE_LIST_SUCCESS: 'BOARD_CREATE_LIST_SUCCESS',
  BOARD_CREATE_LIST_FAILED: 'BOARD_CREATE_LIST_FAILED',
  BOARD_CARD_CREATE: 'BOARD_CARD_CREATE',
  BOARD_CARD_CREATE_SUCCESS: 'BOARD_CARD_CREATE_SUCCESS',
  BOARD_CARD_CREATE_FAILED: 'BOARD_CARD_CREATE_FAILED',
}
