export default {
  BOARD_JOIN: 'BOARD_JOIN',
  BOARD_LEAVE: 'BOARD_LEAVE',
  BOARD_CREATE_LIST: 'BOARD_CREATE_LIST',
  BOARD_CREATE_LIST_SUCCESS: 'BOARD_CREATE_LIST_SUCCESS',
  BOARD_CREATE_LIST_FAILED: 'BOARD_CREATE_LIST_FAILED',
}
